In [38]:
import pandas as pd
import numpy as np

In [42]:
#creating a simple array of string
data=['call me  tonight', 'i will call u tmrw', 'please dont call me', 'waiting for call']

# Steps in Text Vectorization
# 1- Import
# 2- Instantiate
# 3- Fit
# 4- Transform

In [40]:
#importing the vectorizer which is used to transform the text into the numerical value
from sklearn.feature_extraction.text import CountVectorizer as cv

In [41]:
#making the classifier
clf=cv()

In [43]:
#fittng the data
clf.fit(data)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [44]:
#to see the individual word in a database
clf.get_feature_names()

['call', 'dont', 'for', 'me', 'please', 'tmrw', 'tonight', 'waiting', 'will']

In [45]:
#transforming the data into numerical values
dtm=clf.transform(data)

In [46]:
dtm

<4x9 sparse matrix of type '<class 'numpy.int64'>'
	with 13 stored elements in Compressed Sparse Row format>

In [47]:
#conversion of dtm to array
dtm.toarray()

array([[1, 0, 0, 1, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 1, 0, 0, 1],
       [1, 1, 0, 1, 1, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 1, 0]], dtype=int64)

In [48]:
#converting into pandas dataframe
pd.DataFrame(dtm.toarray(), columns=clf.get_feature_names())

call  dont  for  me  please  tmrw  tonight  waiting  will
0     1     0    0   1       0     0        1        0     0
1     1     0    0   0       0     1        0        0     1
2     1     1    0   1       1     0        0        0     0
3     1     0    1   0       0     0        0        1     0

In [69]:
#prediction of new data
test=['dont call me tonight....okay']

In [70]:
test_dtm=clf.transform(test)

In [71]:
test_dtm.toarray()

array([[1, 1, 0, 1, 0, 0, 1, 0, 0]], dtype=int64)

In [72]:
pd.DataFrame(test_dtm.toarray(), columns=clf.get_feature_names())

call  dont  for  me  please  tmrw  tonight  waiting  will
0     1     1    0   1       0     0        1        0     0

In [73]:
#its just neglected the word okay...since it is not present in the training test

# SPAM AND HAM

In [148]:
#loading the dataset
url=r"C:\Users\hp\Desktop\ML\pycon-2016-tutorial-master\data\sms.tsv"
sms=pd.read_table(url, header=None, names=['label', 'msg'])

In [149]:
sms.shape

(5572, 2)

In [150]:
sms.head()

label                                                msg
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [151]:
#couting of a particular word in a table
sms.label.value_counts()

ham     4825
spam     747
Name: label, dtype: int64

In [152]:
#checking of null values
sms.isnull().sum()

label    0
msg      0
dtype: int64

In [153]:
typ=pd.get_dummies(sms['label'], drop_first=True)
sms=pd.concat([sms, typ], axis=1)
sms.drop(['label'], axis=1, inplace=True)
sms.head()

msg  spam
0  Go until jurong point, crazy.. Available only ...     0
1                      Ok lar... Joking wif u oni...     0
2  Free entry in 2 a wkly comp to win FA Cup fina...     1
3  U dun say so early hor... U c already then say...     0
4  Nah I don't think he goes to usf, he lives aro...     0

In [154]:
X=sms['msg']
Y=sms['spam']

In [155]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, Y, test_size=.25, random_state=0)

In [156]:
from sklearn.feature_extraction.text import CountVectorizer as cv

In [157]:
vect=cv()

In [158]:
x_train_dtm=vect.fit_transform(X_train)

In [159]:
x_test_dtm=vect.transform(X_test)

In [160]:
from sklearn.naive_bayes import MultinomialNB as nb

In [161]:
clf=nb()

In [163]:
clf.fit(x_train_dtm, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [165]:
y_pred=clf.predict(x_test_dtm)

In [166]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.9885139985642498

In [167]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[1206,    2],
       [  14,  171]], dtype=int64)

In [169]:
#incorrectly spam classified
#false positive
X_test[(y_pred > y_test)]

4382               Mathews or tait or edwards or anderson
1290    Hey...Great deal...Farm tour 9am to 5pm $95/pa...
Name: msg, dtype: object

In [170]:
#incorreclty ham classified
#false negative
X_test[(y_pred < y_test)]

684     Hi I'm sue. I am 20 years old and work as a la...
731     Email AlertFrom: Jeri StewartSize: 2KBSubject:...
2575    Your next amazing xxx PICSFREE1 video will be ...
1940    More people are dogging in your area now. Call...
751     Do you realize that in about 40 years, we'll h...
4213    Missed call alert. These numbers called but le...
4298    thesmszone.com lets you send free anonymous an...
3864    Oh my god! I've found your number again! I'm s...
5449    Latest News! Police station toilet stolen, cop...
1430    For sale - arsenal dartboard. Good condition b...
2247    Hi ya babe x u 4goten bout me?' scammers getti...
3460    Not heard from U4 a while. Call me now am here...
2823    ROMCAPspam Everyone around should be respondin...
2402    Babe: U want me dont u baby! Im nasty and have...
Name: msg, dtype: object

In [171]:
X_test[2402]

'Babe: U want me dont u baby! Im nasty and have a thing 4 filthyguys. Fancy a rude time with a sexy bitch. How about we go slo n hard! Txt XXX SLO(4msgs)'

In [173]:
Y[2402]

1